package com.aimsgraph.ingest.validator;

public enum ErrorType {
  INVALID_ID,
  MISSING_FIELD,
  SUMMARY_LENGTH_INVALID,
  BODY_EMPTY,
  PLACEHOLDER_DETECTED,
  UNKNOWN_REFERENCE,
  INVALID_SLUG_FORMAT,
  SELF_REFERENCE,
  INVALID_FRONTMATTER,
  EMPTY_CONTENT
}
